name: loredart_nn
description: Simple library for creating and training Deep Neural Networks, written in pure Dart
version: 0.0.1+2
homepage: https://github.com/suntez/loredart_nn
repository: https://github.com/suntez/loredart_nn

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  normal: ^0.6.0

dev_dependencies:
  lints: ^1.0.0
  csv: ^5.0.1
