name: loredart_nn
description: Small package for creating, training and saving neural network, written in pure Dart. Supports MLPs and CNNs.
version: 2.0.0

homepage: https://github.com/suntez/loredart_nn
repository: https://github.com/suntez/loredart_nn

publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'


dependencies:
  loredart_tensor: '>=1.1.0'
  dolumns: ^2.0.1


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  csv: ^6.0.0
