name: flutter_mnist_xmpl
description: Flutter app with loredart_nn Neural Network.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  loredart_nn:
    path: "../../"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/ce_mnist/
